services:
  - type: web
    name: attendance-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: DATABASE_URL
        sync: false
